FROM python:3.10-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de dependencias al contenedor
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del proyecto al contenedor
COPY . .

# Exponer el puerto 5000
EXPOSE 5000

# Comando para ejecutar Flask
CMD ["flask", "run", "--host=0.0.0.0", "--app=app"]


